### PR TITLE
Add Nautical units

### PR DESCRIPTION
**Pull request by ninelima**
This is a first draft with Nautical units in addition to Metric and Imperial.
I did some limited testing, but not very in depth. 
If there are some test-cases, it would be useful to run them, to see that nothing got broken.

### CODE REVIEW

**Comment by ninelima** [comment]
I would probably have been better to use a branch.

**Comment by sikmir** [comment]
I would suggest you to split this PR into 2 ones:

1. Add Afrikaans translation
2. Add Nautical units

**Comment by tumic0** [comment]
Hi,
First sorry for answering the pull request that late, but in the last days I was trying to spend all time that I have for GPXSee toimplement the GeoTIFF feature and related stuff for the 5.0 release.

Second - I'm sorry, but I won't accept the request. There are two reasons. The first one is technical - you mix multiple things in one pull request. To merge the changes they would have to be splitted like sikmir suggests. The second one is that I do generally not accept code pull requests at the moment for reasons described in issue #26. Generally - nautical units are a good and quiet easy enchancement and I will add them as soon as I'm finished with the remaining 5.0 stuff.

For the moment I can accept a translation pull request, if you separate it from the other changes.

**Comment by ninelima** [comment]
Not a problem.  I am still a little bit unfamiliar with using git and
github for collaboration yet.
I was actually thinking afterward that I should have rather done it on
a branch. I will do that and then re-submit the MR. In the meantime
reject the MR.

----- Original Message -----

**Comment by ninelima** [comment]
The nautical units is not really important. I just wanted to get the "feel" for your code-base and I find the best the best way is to actually "do" something. 
I simply picked a topic which I thought  would be simple and not likely to introduce bugs.

**Comment by sikmir** [comment]
> I am still a little bit unfamiliar with using git and github for collaboration yet.

That's OK)
The best way to do it:
1) create feature branch
2) ... make required commits
3) squash all your commits into single one
4) rebase your branch on top of master
5) create PR
6) delete branch after merge

That makes it easy to mantainer to review your PR.

**Comment by ninelima** [comment]
Thanks for the instructions.
I will give it a try.


------ Original Message ------

**Pull request closed without merging**
