### PR TITLE
Remember and reuse last used tracks directory

### PR DESCRIPTION
**Pull request by mkroehnert**
* openFile() always try to open last used tracks directory
* the last used tracks directory is stored in QSettings
* $HOME is used as default if the last used tracks directory does not exist

### CODE REVIEW

**Comment by tumic0** [comment]
Sorry, but I do not accept code merge requests for the project at the moment because of the following reasons:

1. I want leave the possibility to distribute GPXsee builds in the OS X/Windows stores under a non-GPL licence open.
2. I want to keep the project a "personal project" for now.

This may change in the feature, but for now you may "only" help the project with bug reports, translations (which can be easily excluded if [1] should happen) and feature requests.

**Comment by mkroehnert** [comment]
Thanks for the answer and too bad, that you can not accept this convenience feature.
But following it, I don't understand the reason for putting the code on GitHub and using the GPL in the first place, since anybody is allowed to create a fork of a GPL codebase.

**Comment by mkroehnert** [comment]
Maybe you could state your rationale on the website/README, so other people don't submit pull requests.

**Comment by tumic0** [comment]
> But following it, I don't understand the reason for putting the code on GitHub and using the GPL in the first place, since anybody is allowed to create a fork of a GPL codebase.

I don't want to discourage people from using GPXsee as GPL software including forking it. But if I would at some time like to use GPXSee under a different license than GPL (which is for example required for the Apple App store) then I would need some kind of contribution agreement from all the contributors (like [Qt](https://www.qt.io/contributionagreement/) for example). And since I'm no lawyer, it is much easier for me not to accept any submits at all than to bother with some lawyer stuff.

**Comment by tumic0** [comment]
> Maybe you could state your rationale on the website/README, so other people don't submit pull requests.

Well, You are the first one with a "reasonable" code pull request... ;-)

**Comment by mkroehnert** [comment]
Thanks for the reasoning and also thanks for the great project.

It is just that this looked like a nice project to contribute to.

**Pull request closed without merging**
