### PR TITLE
Update gpxsee_en.ts

### PR DESCRIPTION
**Pull request by sikmir**
```
$ lupdate -locations absolute -pluralonly gpxsee.pro -ts lang/gpxsee_en.ts
```

### CODE REVIEW

**Comment by tumic0** [comment]
I don't think that this has any effect for English as the singular version gets never shown (there is the file name instead, see the code). It's only needed for languages like Czech, where you have a different plural form for n = <2, 3> and n>3.

**Comment by sikmir** [comment]
I see:
https://github.com/tumic0/GPXSee/blob/473d03cf1fe7e476eeda227dbf60a8fdafc4dd65/src/GUI/gui.cpp#L1399-L1404

**Comment by sikmir** [comment]
On the other hand, it looks a bit wierd:
Screenshot_2020-06-28 GPXSee Translations — English

**Comment by tumic0** [comment]
I can merge it to make Weblate happy if you reopen it. Usually I don't like to have stuff that does nothing in the code, but here it makes sense to keep it there for some kind of "completeness".

**Pull request merged**
