### PR TITLE
WheelLog CSV support prototype

### PR DESCRIPTION
**Pull request by trundev**
This is an experimental version to support the logs generated by the WheelLog Android app.

These files are with CSV extension, which collide with the Garmin way-point format. I've made some hack in the csvparser.cpp to support both. This is not a best solution, but the other ones would require more changes. Please advice.

At the moment only the speed, power and system-temperature are visualized. The other parameters are also important, but I'm planning to add a separate tab to include all the graphs combined. This would be very useful to analyze the vehicle performance, failures, overheat, etc. Do you think this is feasible?

For more details and some sample data, please check this "release":
  https://github.com/trundev/GPXSee/releases/tag/WL-proto-2019.04

### CODE REVIEW

**Comment by tumic0** [comment]
Like described in the CONTRIBUTING.md file, GPXSee is (at the moment) an open source but not open contribution project. However, even if I would accept code patches, I would not accept this one for several reasons. The main reason is that it is - like you mentioned - an ugly hack. If there should be support for multiple CSV based formats, it would have to be done properly and in some general way like it is for example in GPSBabel.

Also note, that I'm generally not in favor of adding support for every new format someone "invents". At the moment there are like hundred GPS log formats out there (look at GPSBabel) and yet people still have the need of inventing their own one...

And last but not least - as a well known E-bike hater, I can hardly add support for E-bike related stuff. That would ruin all my laboriously built reputation... ;-)

**Comment by trundev** [comment]
Your arguments looks completely reasonable. It appears, I've missed to read the CONTRIBUTING.md. Please excuse me for the confusion.

I find you tool very useful to analyse of multiple outdoor activities. I'd kindly ask for you permission to allow me make some changes in a separate branch, for strictly personal/hobbyist needs. Possibly, as the code is in a public repository, this is explicitly allowed (I'm not familiar with these licences), but I'd prefer not to be hated :-).

**Comment by tumic0** [comment]
The code is GPLv3 so you can fork it and modify it and I'm absolutely ok with that. It's just that the changes won't most probably be merged into the "official" GPXSee master branch.

**Comment by trundev** [comment]
Ok, thank you for this clarification. Please excuse me for bothering you.

**Pull request closed without merging**
