### PR TITLE
Update gpxsee_ru.ts, gpxsee_fi.ts

### PR DESCRIPTION
**Pull request by sikmir**
1. `lupdate gpxsee.pro`
2. translate new strings (c535632eb6c55b19c21a199f01092285953dec3c, e9ef68a81ca792eb22e8722da8531f11d0250bbf)

### CODE REVIEW

**Comment by tumic0** [comment]
Thank you very much for the translation, but unfortunately those few strings will completely change (again, sorry) until 5.0 is released.

I have decided to switch from the list files to separate files for every online map in 5.0. This will not only allow to add additional parameters (for example map bounds) to the definitions, but primarily the files can later be easily extended to support WMS/WMTS maps.

**Comment by sikmir** [comment]
OK, we can keep this PR open, and I'll update and rebase as strings change. And before 5.0 release you can merge it.

**Comment by tumic0** [comment]
So, the current localization strings should be the final one that will be released in 5.0. The whole format description section was dropped (will be only on the program homepage), so updating the ts files should not be much work for you.

**Comment by sikmir** [comment]
@tumic0 Updated.

**Pull request merged**
