### PR TITLE
added italian translation

### PR DESCRIPTION
**Pull request by giomba**
I'm not an expert user of this software, I only use it for GPX, and I've never encountered some terms, in particular, in order to complete the translation I need a more in-depth explanation of the following terms:
- "cadence"
- "routes" (particularly what's the actual difference with tracks; I've always got tracks)
- "Item Count (>1)" what does this actually do?
- "Links" I don't have them in my tracks, are these hyperlinks (www) or links?

### CODE REVIEW

**Comment by sikmir** [comment]
> "cadence"

https://it.wikipedia.org/wiki/Cadenza_di_pedalata

> "routes"

https://it.wikipedia.org/wiki/GPS_eXchange_Format: tracks (tracce), routes (percorsi).

> "Links"

"A link to an external resource (Web page, digital photo, video clip, etc) with additional information." ( See [here](https://www.topografix.com/GPX/1/1/#type_linkType))

**Comment by tumic0** [comment]
_"Item Count (>1)"_ - Selects whether to show the number of tracks/routes/waypoints in the printed (PDF export) document's header.

**Comment by tumic0** [comment]
While @sikmir is right, that Weblate is generally prefered over "plain" pull requests (due to an larger translator community watching Weblate rather than this repo and the tooling provided) I would never say that it is required to use it. Especially in the initial language commit as many people are used to Qt's Linguist and can work much faster using it than using Weblate.

On the other hand - there is still some work on GPXSee that needs to be done to fully integrate the new language, so the pull request is not complete anyway. But that's fine, I can do the remaining parts myself unlike the translation itself :-)

**Comment by giomba** [comment]
Thank you @sikmir and @tumic0 for your suggestions; I have updated the translation accordingly.
Sorry for not having noticed the Weblate website before; I hope you will be able to use the translation anyway.

**Pull request merged**
