### PR TITLE
Add Afrikaans language

### PR DESCRIPTION
**Pull request by ninelima**

### CODE REVIEW

**Comment by tumic0** [comment]
Much better, than the previous pull request, but still not ideal. Can you please make the pull request against the current master? Some of the strings have changed meanwhile.Thanks

**Comment by sikmir** [comment]
It's bad idea to use master branch, use feature branch instead. And then rebase it on top of master to keep it in sync with upstream.

**Comment by tumic0** [comment]
Closing at least this one. I'm letting the later pull request open, but to accept it, I need it updated to the latest version (doesn't necessary mean all strings have to be translated).

**Comment by sikmir** [comment]
@tumic0 By the way, git workflow (create GH account, create fork, create branch, make commit, create PR, sync with upstream, ..., + install Qt Linguist) can be pretty difficult for translators (who are not developers). So, maybe it worth looking at something like [Weblate](https://weblate.org), it's free, open source and extremely easy for translators and project maintainers. It may encourage someone to translate.

**Comment by tumic0** [comment]
Well, Weblate is also on my TODO list :-)

**Comment by sikmir** [comment]
Just in case, @ninelima, welcome to [Weblate](https://hosted.weblate.org/projects/gpxsee).

**Pull request closed without merging**
