### PR TITLE
Improve toolbar look and feel on macOS

### PR DESCRIPTION
**Pull request by bwalle**

### CODE REVIEW

**Comment by tumic0** [comment]
It's already there: https://github.com/tumic0/GPXSee/blob/a56c02953f0baf973808dce4e60742c97e96a202/src/GUI/gui.cpp#L85

**Comment by bwalle** [comment]
The reason why I made that pull request is that the released version  is missing that integration:

Bildschirmfoto 2020-04-04 um 10 08 19

However, I didn’t look in the code; yes, the line is there. I think the problem it is an quite old version of Qt in the shipped binary. I’m using macOS 10.15.4.

**Comment by tumic0** [comment]
Well the toolbar in Qt on Mac is a never ending story of failures... The "quite old Qt version" is used by the official GPXSee builds because of a one and only reason - a [completely broken toolbar](https://bugreports.qt.io/browse/QTBUG-81791) in any newer version.

**Comment by bwalle** [comment]
Oh, sorry. 

BTW: GPXsee is great :+1:

**Pull request closed without merging**
